# Instructions to be run by Travis CI before every push to GitHub, awaring us of any problem

language: python
python:
  -"3.6"
services:
  - docker
before_script: pip install docker-compose
script:
  - docker-compose run app sh -c "python manage.py test && flake8"